feedback.urgencia.critica.nota-maxima=4
feedback.relatorio.cron=0 0 8 ? * MON
feedback.admin.email=${FEEDBACK_ADMIN_EMAIL:admin@tc4feedback.com}

quarkus.log.level=INFO
quarkus.log.category."org.acme".level=DEBUG

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=tc4_user
%dev.quarkus.datasource.password=tc4_password
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/feedback_db
%dev.quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.mailer.mock=true
%dev.quarkus.mailer.from=noreply@tc4feedback.com

# Perfil PRODUÇÃO (Azure)
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
%prod.quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
%prod.quarkus.datasource.jdbc.additional-jdbc-properties.sslmode=require
%prod.quarkus.hibernate-orm.database.generation=update
%prod.quarkus.hibernate-orm.log.sql=false

%prod.quarkus.mailer.mock=false
%prod.quarkus.mailer.from=${MAILER_FROM:noreply@tc4feedback.com}

%prod.azure.communication.connection-string=${AZURE_COMMUNICATION_CONNECTION_STRING}

%prod.azure.application-insights.connection-string=${APPLICATIONINSIGHTS_CONNECTION_STRING}

%prod.quarkus.azure-functions.app-name=tc4-feedback-functions
%prod.quarkus.azure-functions.resource-group=rg-tc4-feedback
%prod.quarkus.azure-functions.region=brazilsouth