# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=tc4_user
quarkus.datasource.password=tc4_password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/feedback_db

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

quarkus.mailer.mock=true
quarkus.mailer.from=noreply@tc4feedback.com

feedback.urgencia.critica.nota-maxima=4

feedback.relatorio.cron=0 0 8 ? * MON

feedback.admin.email=admin@tc4feedback.com

quarkus.log.level=INFO
quarkus.log.category."org.acme".level=DEBUG